### ISSUE TITLE
Missing city 0 at start and end of the path

### ISSUE THREAD

**Issue by TheRizzock** [matago/BadSanta#3]
Currently, the path your generating is of len = 197770, the data is also len=197770. The path does not start at 0 or end at 0 (see sample below).

```
Path
133460
127723
55524
......
75201
52641
119881
124659
```

**Comment by matago** [comment]
If it is required to start and end at zero for submission we can alter the upload and the save functions so that it rolls the array and appends a zero

**Comment by TheRizzock** [comment]
I made some updates to do this (I think). I going to pull the last and push my current

**Comment by matago** [comment]
word

**Comment by TheRizzock** [comment]
Even with this we are still off on the fitness Kaggle upload = 447673377.63, 
scriptCalc = 445816365.08483905 see #4

**Comment by dkowalsky7** [comment]
#4

**Comment by matago** [comment]
#5
